Open-Eye-Im-Developer/MoGakGo-FE

app/_common/components/ClientProvider.tsx
app/layout.tsx

close #13 
- [공식홈페이지 참고](https://tanstack.com/query/v4/docs/framework/react/guides/ssr#using-nextjs)

chore: clientprovider 설정

---

app/(map)/_components/Map.tsx
app/page.tsx

- 이전 PR 리뷰 반영해서 지도 페이지 이름을 Map.tsx로 변경하고, 컴포넌트 폴더로 이동했습니다
close #53

[refactor] 지도 컴포넌트 이름 변경 및 폴더 이동

---

app/layout.tsx

- layout.tsx에 중복 import된 globals.css 정리

[cleanup] globals.css 파일 중복 import 제거

---

app/achievements/_components/AchievementItem.tsx
app/achievements/_components/AchievementList.tsx
app/achievements/_components/AchievementProgress.tsx
app/achievements/_test/calculateAchievement.test.ts
app/achievements/_utils/calculateAchievement.ts
app/achievements/page.tsx

[style] 업적 페이지 view 구현

---

app/(map)/_components/Map.tsx
app/_common/types/position.ts
app/auth-mylocation/_components/MyLocationAuth.tsx
app/auth-mylocation/_hooks/useQueryGeoAreaCode.ts

[fix] GeoAreaCode 타입 추가 후 관련 파일 수정

---

app/page.tsx
app/signup/page.tsx
next.config.mjs

- useSearchParams가 사용되는 page인 '/'와 '/signup' 페이지에 Suspense가 필요하여 추가하였습니다. [관련 공식 문서](https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout)
close #96

[chore] build 시 에러해결

---

app/(map)/_components/Map.tsx
app/_common/api/location.ts
app/_common/store/usePositionStore.ts
app/_common/types/position.ts
app/_common/utils/getGeolocation.ts
app/auth-mylocation/_components/MyLocationAuth.tsx
app/auth-mylocation/_hooks/useMutationAuthMyLocation.ts
app/auth-mylocation/_hooks/useQueryGeoAreaCode.ts

- 추가로 비슷한 import 에러가 있는 파일 있다면 알려주세요. 해당 브랜치에서 함께 수정하겠습니다.
close #90

[fix] position type 파일명 refactor 이후 잘못된 경로 수정

---

app/_common/components/NavigationBar.tsx
app/_common/store/useAuthStore.ts
app/auth-mylocation/_components/MyLocationAuth.tsx
app/project/_components/ButtonRequest.tsx
app/project/_components/ProjectCardFront.tsx

- `AuthStore`의 `user` 객체의 타입이 `User`에서 `User | null`로 변경되면서 이에 대응되도록 조건문이 추가 되었습니다, 
추가된 코드 중 잘못된 부분은 없는지 한번씩 확인해주세요.
- 공통 `NavigationBar.tsx`
- `project`의 `ButtonRequest.tsx`, `ProjectCardFront.tsx`
- `auth-mylocationm`의 `MyLocationAuth.tsx`
close #101

[fix] AuthStore user 객체 기본값 변경

---

next.config.mjs

- next.config.js 설정 후 build 시 해당 에러가 발생하여 [다음 링크](https://github.com/vercel/next.js/issues/40155)의 해결방법을 적용하였습니다.
- next.config.js 설정 이후 해당 에러가 발생하고 있습니다. 팀 내부에서 확인한 결과로는 저에게만 발생하는 에러로 판단되어 우선 해결하지 않았습니다. 에러 해결 방법은 [다음 링크](https://github.com/shadowwalker/next-pwa/issues/288)에서 발견했습니다.

[chore] redirects 설정 추가

---

app/chat/[id]/_components/MessageInput.tsx

[fix] user 정보 null 오류 수정

---

app/_common/components/ClientProvider.tsx
package-lock.json
package.json

- react-query devtools 설치
close #128

[chore] react-query devtools 설치

---

next.config.mjs

[chore] next.config.js 설정 변경

---

tailwind.config.ts

- NeoRed
- NeoYellow
- NeoGreen
- NeoBlue
close #156

[refactor] 브랜드 컬러 tailwind config 설정

---

app/chat/[id]/_components/MessageInput.tsx
app/chat/_api/index.ts
app/chat/_api/useDeleteChatRoom.tsx
app/chat/_components/Chat.tsx
app/chat/_components/OptionButton.tsx

[feat] 채팅방 활성화 상태 및 나가기 기능 구현

---

app/_common/shadcn/ui/dropdown-menu.tsx

- @bgyoons @coggiee 
#151 dropdown-menu 사용하는 것을 확인하고 스타일 수정하였습니다!

[style] dropdown-menu 스타일 수정

---

app/globals.css

[refactor] 일반 css를 @apply로 변경

---

app/_common/hooks/useSearchTokens.ts
app/review/_components/ReviewForm.tsx
next.config.mjs

- redirects의 '/도메인/:slug*'로 설정하면 도메인을 포함한 모든 경로를 차단하므로 router로 대체하였습니다.
close #169

[fix] redirects 설정 수정 (회원가입, 리뷰)

---

app/_common/shadcn/ui/accordion.tsx

1. outline
2. default
close #182

[style] accordion variant 옵션 추가

---

app/project/_constants/formSchema.ts

- 기존에는 시작 시각보다 종료 시각이 클 때, **종료 분이 항상 시작 분보다 컸어야 하는 오류**를 **같아도 되는 조건을 추가**하여 수정
close #175

[fix] 프로젝트 생성 시간 설정 오류

---

app/(map)/_components/Map.tsx

[fix] 움직이는 배경 이미지 보이지 않는 문제 수정

---

app/_common/shadcn/ui/button.tsx

- 기존 모바일 환경에서 버튼 transform
- 수정된 버튼 transform
close #174

[style] button hover => active로 가상선택자 변경

---

app/chat/[id]/_components/ProjectInfo.tsx

[fix] 카카오 장소 바로가기 API 동작 오류

---

app/_common/components/ProfileCard.tsx
app/project/_components/DialogMoreInfo.tsx
app/project/_components/FormPlace.tsx
app/project/_components/FormTag.tsx
app/project/_components/FormTime.tsx
app/project/_components/InfoPopover.tsx
app/project/_components/PlaceItem.tsx
app/project/_components/PlaceList.tsx
app/project/_components/ProjectCardBack.tsx
app/project/_components/ProjectCardContainer.tsx
app/project/_components/ProjectCreateForm.tsx
app/project/_hooks/useCreateProjectMutation.ts
app/project/_hooks/useDebounceSearch.ts
app/project/_hooks/useGetRequestListQuery.ts
app/project/_hooks/useInfiniteScroll.ts
app/project/_hooks/useTagSelect.ts
app/project/_types/type.d.ts

- 기존 코드로 인해, 다른 PR도 배포에 오류가 발생합니다. merge되면 정상적으로 배포될 것으로 생각합니다.
- type.d.ts에서 원래 잘 읽어왔는데 갑자기 오류가 발생해서, 원인이 뭔지 모르겠습니다. 
원인에 대해 아시면 공유 부탁드립니다. 😭
close #219

[fix] import type 오류 수정

---

app/project/_components/ProjectManageSection.tsx

[style] 프로젝트 페이지 배경 이미지 적용

---

app/achievements/_components/AchievementList.tsx

[fix] import 에러 수정
