babel.config.js
package-lock.json
package.json

- close #8 
- 참고링크: [jest 공식](https://jestjs.io/docs/29.5/getting-started)
1. babel 사용시 설치
`npm install --save-dev babel-jest @babel/core @babel/preset-env`
1-2. babel.config.js에 아래와 같이 설정
```
module.exports = {
presets: [['@babel/preset-env', {targets: {node: 'current'}}]],
};
```
2. typescript 사용시 설치
`npm install --save-dev @babel/preset-typescript`
2-1. babel.config.js에 아래와 같이 추가 설정
```
module.exports = {
presets: [
['@babel/preset-env', {targets: {node: 'current'}}],
'@babel/preset-typescript',
],
};
```
2-2. typescript 사용시 설치 2
`npm install --save-dev ts-jest`
2-3. typescript definition을 위해 필요한 설치 (27.4.0 이상이면 이거를 권장)
`npm install --save-dev @types/jest`
1. 외부 export 파일을 import 할 수 없음. Node.js는 기본적으로 CommonJS 모듈 시스템을 사용하므로, import와 export 구문을 사용하려면 몇 가지 설정이 필요. 이를 위하여 babel 사용시 필요한 …

chore: babel, typescript 사용을 위한 jest 필수 패키지 설치 및 설정파일 추가

---

app/_common/test/checkInstanceOfResponseError.test.ts
app/_common/types/response.types.ts
app/_common/utils/checkInstanceOfResponseError.ts

```tsx
export const instance = axios.create({
baseURL: `${BASE_URL}${SERVER_VERSION}`,
headers: {
"Content-Type": "application/json",
Accept: "application/json",
Authorization: `Bearer ${accessToken}`,
},
validateStatus: status => status < 500, // 추가
});
```
현재 범님이 작업해주신 axios instance를 기준으로 `validateStatus: status => status < 500` 코드를 추가했습니다. 
response status가 500 미만인 경우에는 400대 에러여도 axios error를 일으키지 않고 데이터로 넘겨주도록 하는(`promise가 resolve됨`) 설정인데 이렇게 하는 경우에 **리액트 쿼리를 쓰게 된다면 400대 에러가 떴을 때 error 객체로 넘어오지 않고 data 객체로 넘어오는 것을 확인**했습니다!
따라서
- 받은 타입이 에러 객체일 때 에러 객체 타입 생성
- 받은 데이터 타입이 ResponseError인지 확인하는 유틸 함수 생성
작업을 통해 아래와 같은 데이터 처리를 하도록 작업을 해보았습니다.
```tsx
const { data, isLoading } = useQueryGeoAreaCode();
if (data) {
if (checkInstanceOfResponseError(data)) {
toast.error(data.message);
} else …
```

[feat] axios validateStatus 설정에 따라 response type 추가 설정

---

app/project/_components/ProjectCardBack.tsx
app/project/_components/ProjectCardFront.tsx
app/project/_styles/card.css

- wiki에는 style 파일을 `컴포넌트이름.styles.ts`로 생성한다고 되어있는데 ts로 스타일을 어떻게 생성하여 적용해야할 지 잘 모르겠어서, 지금은 일단 `_styles/스타일파일`로 생성을 해뒀습니다.
- 관련해서 조언해주시면 수정해서 반영하겠습니다!
https://forum.blocsapp.com/t/css-backface-visibility-issue-solved/20229
https://stackoverflow.com/questions/42744573/backface-visibility-not-working-in-safari/45145977#45145977
close #41

[fix] style 속성 브라우저 호환성 버그 수정

---

app/(map)/_components/Map.tsx
app/(map)/_components/RankInfo.tsx
app/_common/components/MapComponent.tsx

- 지도 확대 시 스크롤 생기는 버그는 scale로 확대 되었을 때 생기는 스크롤이어서 루트 태그에서 overflow: hidden 속성을 주어 해결했습니다.
- touch-action: none을 통해 지도를 손가락이나 더블탭으로 확대/축소를 막았습니다.
- 놓친 부분이 있거나 잘못된 스타일 값을 주었다면 말씀 주시면 감사하겠습니다!
close #55

[fix] 지도 확대 시 스크롤 생기는 버그 및 손가락 확대 막기

---

app/project/_hooks/useTagSelect.ts

- isComposing 옵션으로 이벤트 발생 여부를 제어하여 중복 입력을 제거했습니다.
close #80

[fix] 프로젝트 생성 폼 한글 입력 2번 되는 문제 수정

---

app/achievements/_components/AchievementDrawer.tsx
app/achievements/_components/AchievementItem.tsx
app/achievements/_components/AchievementList.tsx
app/achievements/_components/AchievementProgress.tsx
app/achievements/page.tsx

기본 업적 페이지 스타일
https://github.com/Open-Eye-Im-Developer/MoGakGo-FE/assets/114740795/35381ac5-f393-4621-ac93-776a5ce51e0e
close #76

[style] 업적 페이지 스타일 수정

---

app/_common/components/NavigationBar.tsx
app/_common/components/NavigationItem.tsx
app/_common/components/NavigationProfile.tsx
app/layout.tsx

https://github.com/Open-Eye-Im-Developer/MoGakGo-FE/assets/101445377/53e05113-00d2-46d2-a794-9aec10615d18
https://github.com/Open-Eye-Im-Developer/MoGakGo-FE/assets/101445377/3c3c4895-b012-4b65-a693-0dffebd858da
https://github.com/Open-Eye-Im-Developer/MoGakGo-FE/assets/101445377/b714705d-ae17-4193-b714-56135f52836f
- 사용자 정보는 API 호출 대신, `useAuthStore`로 사용 
- Shadcn의 `Sheet`을 사용
<del>- `root layout`에 `NavigationBar`를 추가했습니다.</del>
<del>  - 로직 흐름을 원활하게 확인할 수 있도록 임시로 추가한 것이므로, 수정이 필요할 수 있습니다.</del>
```html
<html suppressHydrationWarning={true}>
<link rel="manifest" href="/manifest.json" />
<meta name="theme-color" content="#ffffff" />
<body>
<ClientProvider>
<ThemeProvider
attribute="class"
defaultTheme="system"
enableSystem
disableTransitionOnChange
>
<section className="flex …
```

[style] 네비게이션 바 구현

---

app/(map)/_api/useGetCardList.ts
app/(map)/_api/useGetRank.ts
app/(map)/_components/CardList.tsx
app/(map)/_components/Map.tsx
app/(map)/_components/ProfileCardItem.tsx
app/(map)/_tests/formatRegionName.test.ts
app/(map)/_utils/formatRegionName.ts
app/_common/api/profile.ts
app/_common/api/project.ts
app/_common/components/LoadingSpinner.tsx
app/_common/components/MapComponent.tsx
app/project/_components/ButtonFollow.tsx
app/signup/_components/SignupForm.tsx

- 프로젝트, 프로필 카드 조회, 밀도 순위에 에러 처리가 필요없으므로 에러 핸들링 코드 삭제 (추후 필요하다면 다시 추가하겠습니다)
- 로딩 시 `LoadingSpinner` 컴포넌트 적용
- 백엔드 api 수정으로 구역별 프로젝트/프로필 카드 초기 조회 때 cursorId 안 들어가도록 쿼리 수정
- `useInfiniteQuery`를 이용하여 무한 스크롤 구현
- `hasNext` 프로퍼티를 사용하여 프로젝트 조회할 때 다음에 조회할 것이 없으면 프로필을 조회하도록 구현
- **현재 에러는 나지 않도록 데이터 반환값을 0번째 인덱스로 하도록 고정해두었지만, 데이터가 부족해서 충분한 테스트를 못한 상태이기 때문에 데이터 반환값을 추후 수정해야 합니다.**
```ts
cardList: {
projectList: projectList.pages[0].data,
profileList: profileList.pages[0].data,
},
```
이렇게 처리해놔서 에러가 나지는 않지만 테스트를 통해 반환값을 수정할 예정입니다. 로직을 수정해야할 수도 있습니다!
- 무한스크롤 구현에서 로직적인 문제가 있는지 궁금합니다.
- 컨벤션이나 명칭이 알아보기 쉬운지, 로직이 쉽게 이해가는지 궁금합니다.
close #68

[feat] 지역별 카드 조회 페이지네이션 로직 구현

---

app/_common/hooks/mutation/useDeleteUser.ts
app/signup/_components/ProfileCard.tsx
app/signup/_components/SignupFinalStep.tsx
app/signup/_components/SignupFirstStep.tsx
app/signup/_components/SignupForm.tsx
app/signup/_components/SignupSecondStep.tsx
app/signup/page.tsx

[style] 회원가입 스크롤 막음 해제 그 외

---

app/signup/_components/ProfileCard.tsx
app/signup/_hooks/useMutationSignup.ts

- 정상적으로 빌드 완료되는 것을 확인했습니다.
close #108

[hotfix] user 객체, developLanguages 타입 관련 문제 해결

---

app/_common/hooks/useSearchTokens.ts
app/signup/_hooks/useQuerySignUpUser.ts

회원가입 후 전역 스토어에 유저 정보를 저장하는 로직(`useMutationSignup.ts`)이 있는 반면,
로그인 후 메인(`Map.tsx`)으로 진입할 때는 깃허브 로그인을 통해 리다이렉션 로직만 수행되고 있습니다. 
따라서 이미 회원가입을 한 유저가 로그인을 진행하는 경우에 스토리지에 유저 정보가 저장되지 않아(스토리지가 비어있는 경우에는 유저 정보가 존재하지 않아) `useAuthStore`를 통해 `user` 객체를 참조한다면 `null` 값으로 조회되어 이 스토어를 쓰게 되는 다른 코드에 영향을 미치게 됩니다.
HOC로 구현된 `WithSearchTokens.ts`는 `Map.tsx`에 진입 시 항상 실행됩니다
유저 정보를 조회하려면 `useQuerySignUpUser.ts` 훅을 써야하는데 정보를 받아오기 위해선 엑세스 토큰이 필요한 상황입니다.
`WithSearchTokens.ts` 내부에 `useSearchTokens.ts` 훅을 통해 엑세스 토큰을 가져오는 로직이 있어서 이 훅에서 가져온 엑세스 토큰을 이용해 `useQuerySignUpUser.ts` 훅을 불러내어 유저 정보를 받아오고, 저장하도록 로직을 구현해보았습니다.
엑세스 토큰이 없으면 `useQuerySignUpUser.ts`을 호출하면 안되므로 옵셔널로 파라미터를 받도록 하여 기본값은 `true`로 하여 `useQuerySignUpUser.ts` 훅을 쓰고 있는 다른 코드에는 영향을 미치지 않도록 했습니다.
아래는 현재 dev 브랜치에서 로그인을 하는 경우와 제가 작업한 브랜치에서 로그인한 경우에 스토리지에 저장되는 것을 …

[fix] 로그인 시 사용자 정보 전역 스토어 저장 로직 구현

---

app/(map)/_api/useGetRank.ts
app/(map)/_components/Map.tsx
app/_common/api/project.ts

- 프로젝트 구역별 밀도 순위를 불러오는 useGetRank 훅에서 throwOnError: false 옵션을 설정해 에러인 경우 흰 화면이 뜨지 않도록 처리
- 에러를 내는 경우 데이터 반환값 추가
아래 화면 기록을 보시면 401 에러가 나도 지도가 나오는 것을 확인할 수 있습니다.
- 더 나은 개선 사항이 있는지 피드백 부탁드립니다 :D
close #120

[fix] 지도페이지 401 에러 처리

---

app/(map)/_api/useGetCardList.ts
app/(map)/_api/useToggleLikeProfile.ts
app/(map)/_components/CardList.tsx
app/(map)/_components/ProfileCardItem.tsx
app/_common/api/profile.ts
app/_common/types/profile.ts
app/page.tsx
app/project/_components/ButtonLike.tsx
app/project/_utils/formatMeetingTime.ts

- 찔러보기 요청/삭제 api 연결
- 성공/실패 시 토스트 메시지 띄움
- `useMutation` 옵션에서 `throwOnError: false`로 지정하여 `try/catch`문을 삭제하고 `onError`에서 에러 핸들링
- 프로필 카드 받아와 찔러보기를 한 상대인지 여부 파악하여 요청한 상대면 찔러보기 버튼에 색이 차 있고, 아닌 경우에는 비어있음
- 찔러보기 버튼 UI는 추후 디자인을 바꿀 예정이기 때문에 스타일링을 주지 않았습니다.
- 로직적인 부분이나 문법, 에러 처리 등 개선할 부분을 편하게 리뷰 주시면 감사하겠습니다.
close #67

[feat] 프로필 카드 찜하기 구현

---

app/(map)/_components/Map.tsx
app/_common/utils/redirect.ts

- 문제 상황
- 로컬 스토리지에 유저 정보가 없는 경우 지도를 클릭하여 해당 구역의 카드 리스트를 조회했을 때 400번대 에러가 떠 화면이 막힘
- 해결 방법
- 클릭 시 유저 정보가 없고, 클릭한 영역이 지도이면 early return을 통해 api 호출 막음
- 토스트 메시지를 띄워 사용자가 `로그인하기` 버튼을 클릭하면 로그인 페이지로 리다이랙트 하도록 처리
- 클라이언트 컴포넌트일 때 next에서 제공하는 `redirect`를 사용할 수 있는 유틸을 생성 ([참고 문서](https://nextjs.org/docs/app/api-reference/functions/redirect#client-component))
- 개선할 수 있는 부분, 로직을 추가해야 할 부분 리뷰 주시면 감사하겠습니다!!
close #125

[fix] 유저 정보가 없는 경우 지도를 클릭했을 때 화면 막히는 에러 해결

---

app/(map)/_api/useGetCardList.ts

- 프로젝트, 프로필 카드 조회에서 useInfiniteQuery에서 받아오는 데이터를 파악하여 반환값을 수정했습니다.
- 아래와 같이 데이터가 반환됩니다. (프로필만 예시로 적어놓음, 프로젝트도 같은 형식)
```js
const profileList = {
"pages": [
{
"data": [
{
"response": {},
"requestYn": false
},
{
"response": {},
"requestYn": false
}
],
"hasNext": true,
"numberOfElements": 3,
"size": 2
},
{
"data": [
{
"response": {},
"requestYn": false
},
{
"response": {},
"requestYn": false
}
],
"hasNext": true,
"numberOfElements": 3,
"size": 2
}
],
"pageParams": [
0,
72
]
}
const newProfileList = profileList.pages.reduce((list, response) => {
return list.concat(response.data)
}, [])
console.log(newProfileList)
// [
//   { response: {}, requestYn: false },
//   { response: {}, requestYn: false },
//   { response: {}, requestYn: false },
//   { response: {}, requestYn: false }
// ]
```
- …

[fix] 프로젝트, 프로필 카드 조회 페이지네이션 반환값 수정

---

app/_common/components/SVGProvider.tsx
app/_common/hoc/withOnMounted.tsx

```ts
/* eslint-disable react/display-name */
/* eslint-disable react-hooks/rules-of-hooks */
import { ComponentType, useEffect, useState } from "react";
function withOnMounted<P extends object>(Component: ComponentType<P>) {
return function (props: P) {
const [isMounted, setIsMounted] = useState(false);
useEffect(() => {
if (typeof window === "undefined") return;
setIsMounted(true);
}, []);
return isMounted && <Component {...props} />;
};
}
export default withOnMounted;
```
- 잘못 작성된 부분이 있다면 말씀해주세요.
[발생한 문제](https://velog.io/@yijaee/serverside-html-matching)
[해결 가능한 방법](https://nextjs.org/docs/messages/react-hydration-error)
close #196

[feat] 마운트 여부 확인하는 HOC 생성

---

app/_common/components/NavigationBottom.tsx
app/_common/hoc/WithNavigation.tsx

- 메뉴바 shadcn 컴포넌트를 통해 하단 네비게이션 바를 생성했습니다. 위치값도 지정해두어 컴포넌트만 쓰면 됩니다.
- pathname을 통해 defaultvalue를 제어하도록 하여 현재 위치한 페이지에서 메뉴바 아이템이 하이라이팅 되게 처리했습니다.
- 아래 이미지들은 예시로 코드를 넣어 캡쳐한 것으로, PR에는 해당 예시 코드가 올라와 있지 않습니다.
- layout에 넣기에는 네비게이션 바가 안 들어가는 부분도 있어보이고, 아직 확실한 결론이 나지 않은 것 같아 넣지 않았습니다.
- 좋은 방법으로 구현한 것인지 궁금합니다.
- 모든 피드백 다 환영입니다. :D
close #189

[style] 네비게이션 하단바 컴포넌트 생성

---

app/_common/components/CustomSonner.tsx
app/_common/utils/toast.tsx
app/layout.tsx

- 글씨 크기 줄이기
- 상단에 토스트가 뜨도록 변경
- 배경색에 하얀색 노출 되는 부분 수정
- 리팩토링 할 부분 공유 주시면 감사하겠습니다!
close #214

[style] sonner toast 스타일, 위치 수정

---

app/(map)/_components/Map.tsx

transition 범위가 opacity 한정으로 visibility 속성이 transition 처리가 되지 않아 끊기며 카드가 닫히는 현상이 발생했습니다.
따라서 transition-all 클래스를 지정하여 범위를 all로 넓혔습니다.
또한 지도 확대(1초) > 카드 나타남 로직으로 카드가 나타날 떄(확대될 때)는 애니메이션 딜레이를 1초 두고, 카드가 사라지는 경우에는 딜레이를 두지 않았습니다.
close #222

[fix] 캐러샐 카드 닫을 때 끊기며 사라지는 버그 해결

---

app/achievements/_components/AchievementList.tsx
app/achievements/_components/ListSortSelect.tsx

[feat] 업적 리스트 정렬 기능 추가

---

app/_common/hooks/useChat.ts
app/chat/[id]/_components/MessageContainer.tsx
app/chat/[id]/_components/MessageInput.tsx
app/chat/[id]/_hooks/useGetPrevMessageList.ts
app/chat/_types/type.d.ts

- 하나의 `Custom Hook`으로 묶은 이유는 2가지 입니다.
1. 두 로직 모두 메시지를 다룬다는 점과 각 로직에서 서로의 로직을 끌어다쓰는 점
2. 채팅 페이지 외 채팅 카드에서도 동일한 로직을 사용한다는 점
-> 코드가 간결해졌고, 동일 로직을 재사용할 수 있습니다.
> 채팅 수신/발신 테스트했습니다!
> 처리되지 않은 로직이 있다면 말씀해주세요.
기본적으로 서버에서 본인이 발신한 메시지도 응답으로 보내주게 되어있습니다. 이를 메시지를 보낸 `senderId`와 `authStore`로 저장되어 있는 사용자 `id`를 비교하여 일치한다면 렌더링하지 않도록 수정했습니다.
배포 후, 실제로 프로젝트를 생성하고 채팅 로직에 대한 검증을 수행해야 합니다.
기존에는 `random`으로 설정했으나, `dayjs()`를 사용하여 메시지의 발신 시점(`string`)을 `id`로 설정했습니다.
이전 PR에서 윤서님이 공유해주신 [nanoid](https://www.daleseo.com/nanoid/) 설치를 고려했으나 이미 설치되어 있는 라이브러리를 사용하는 것이 비용이 적다고 판단했고, **메시지의 발신 시점**으로도 충분히 동일한 `id`가 발생하지 않을 것이라고 판단했습니다.(현재 `dayjs().format("YYYY-MM-DDTHH:mm:ss:SSS")` 밀리세컨드까지 계산)
close #228

[refactor] WebSocket 구현 방식 리팩토링

---

app/_common/components/ProfileCard.tsx
app/globals.css
app/project/_components/ProjectCardContainer.tsx
app/project/_components/ProjectCardFront.tsx
app/project/_components/ProjectManageSection.tsx

- 기존에 사용하던 `useQueryAchievements` 쿼리 훅을 사용했습니다.
- 업적을 의미하는 `achievementTitle`에서 `achievementId`로 변경됨에 따라 업적을 가져오는 로직을 추가했습니다.
close #250

[refactor] 프로젝트 카드 & 프로필 카드 유저 업적 수정
